etcd:
  userName:
  password:
  secret:  # etcd 配置密钥

mysql:
  dbMysqlUserName: ruihong #mysql用户名
  dbMysqlPassword: RuiHong@008 # mysql密码

mongo:
  dbUserName:  #mongo用户名
  dbPassword:   #mongo密码

redis:
  dbUserName:
  dbPassWord: 123456 #redis密码

kafka:
  SASLUserName:
  SASLPassword:

credential:
  minio:
    endpoint: http://storage-online.idong.ren:10005 #发图片视频文件需要填写
    accessKeyID: FH3QnhQPVqs7aINy  # ruihong/ruihong123.
    secretAccessKey: 6V03QqET95cSPjt90MNa2N0pmVYtgumw

secret: tuoyun #建议修改

tokenpolicy:
  accessSecret: "open_im_server" #token生成相关 建议修改
  accessExpire: 90 #token过期时间（天） 默认即可

messageverify:
  friendVerify: false #发送消息是否验证好友关系 false表示不验证好友关系

push:
  getui:
    pushUrl: "https://restapi.getui.com/v2/$appId"
    masterSecret: ""  #需添加
    appKey: ""  #需添加
    enable: false  #true启动个推推送

